export const GET_USERS_BEGIN = "GET_USERS_BEGIN";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_SINGLE_USER = "GET_SINGLE_USER";
export const GET_STORED_USER = "GET_STORED_USER";
export const SORT_BY_HEADER = "SORT_BY_HEADER";
export const UPDATE_PAGE = "UPDATE_PAGE";
